name: Parse JSONC
on:
  workflow_dispatch:

jobs:

  parse:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

       - name: Parse JSONC
         shell: pwsh
         run: |
            function Get-JsoncContent {
                param ([string]$Path)
                $raw = Get-Content $Path -Raw
                $raw = $raw -replace '(?m)^\s*//.*$', ''
                $raw = $raw -replace '(?s)/\*.*?\*/', ''
                return $raw | ConvertFrom-Json
                    }

              $config = Get-JsoncContent "config.jsonc"

            Write-Host "Targets R0:"
            $config.Targets_R0

 


