name: Composite action

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: DNS test
      #   shell: pwsh
      #   run: |
      #     Write-Host "Runner OS:"
      #     systeminfo | Select-String "OS Name","OS Version"

      #     Write-Host "`nDNS resolution test:"
      #     Resolve-DnsName api.github.com -ErrorAction Continue

      #     Write-Host "`nConnectivity test (TCP 443):"
      #     Test-NetConnection api.github.com -Port 443

      #     Write-Host "`nProxy environment variables:"
      #     Get-ChildItem Env: | Where-Object Name -match 'PROXY'

      - name: Parse config
        id: parse
        uses: RonnyVanDessel/composite_test_pws@main
        with:
          dscfile: "DotNET_DSC 1_v4.winget"

      