name: Composite action

on:
  
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse config
        uses: RonnyVanDessel/composite_test_pws@v1.1
        with:
          path: Params.jsonc

      - name: Result
        run: echo "Targets = ${{ steps.parse.outputs.targets_r0 }}"