name: Composite action

on:
  
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse config
        uses: RonnyVanDessel/parse-jsonc@v1
        with:
          path: config.jsonc

      - name: Result
        run: echo "Targets = ${{ steps.parse.outputs.targets_r0 }}"