
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Parse JSONC
        shell: pwsh
        run: |
          function Get-JsoncContent {
              param ([string]$Path)
              $raw = Get-Content $Path -Raw
              $raw = $raw -replace '(?m)^\s*//.*$', ''
              $raw = $raw -replace '(?s)/\*.*?\*/', ''
              return $raw | ConvertFrom-Json
          }

          $config = Get-JsoncContent "params.jsonc"

          Write-Host "Targets R0:"
          $config.Targets_R0
          $config.Targets_R1
          $config.Displayname


